DESIGN_NAME: tinynoc_wrapper

VERILOG_FILES:
  - dir::../rtl/input_fifo.sv
  - dir::../rtl/route_decode.sv
  - dir::../rtl/round_robin_arbiter.sv
  - dir::../rtl/qos_arbiter.sv
  - dir::../rtl/switch_fabric.sv
  - dir::../rtl/tinynoc_top.sv
  - dir::../rtl/tinynoc_wrapper.sv

CLOCK_PORT: clk
CLOCK_PERIOD: 20.0

FP_CORE_UTIL: 40
FP_ASPECT_RATIO: 1

PDK: ihp-sg13g2
STD_CELL_LIBRARY: sg13g2_stdcell

